import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './index.css';
import Header from '@/components/header/Header';
import RecoilContext from '@/context/RecoilContext';
import { useEffect } from 'react';
import AuthProvider from '@/components/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Movie Trip',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <RecoilContext>
                    <AuthProvider />
                    <Header />
                    <main className="w-full h-full">{children}</main>
                </RecoilContext>
            </body>
        </html>
    );
}
